### ISSUE TITLE
Try to deliver receipt at least once, even if TTL expired

### ISSUE THREAD

**Issue by idelpivnitskiy** [webpush-wg/webpush-protocol#112]
According to the discussions on #91 we know, that delivery receipt could be send to the AS even if push message resource is already removed from the PS:
- Information for the receipt could be encoded in the push message resource.
- Another case: think that most PS implementations will not totally delete information about push message after TTL expiration. They will delete only the body, because it's encrypted and store all headers and resources for the analytical purposes.

Also a _Full Reliability_ was chosen for acknowledgements: https://www.ietf.org/proceedings/93/slides/slides-93-webpush-1.pdf (slide 18).

After summarizing all of this we may define MUST or SHOULD keyword for sending receipt to the AS at least once even if TTL of the push message expired, but acknowledgement from the UA was received. In this case 410 (Gone) should be send to the AS only if UA was unavailable and no attempt was made to deliver a push message.

For me, the _Full Reliability_ means that receipt must be send to the AS in any case.

**Comment by jrconlin** [comment]
I will note that for our implementation, TTL=0 messages are never stored. Information about the transaction is logged, but not retrievable or re-callable by the application. Requiring ACK for TTL=0 increases our storage costs, possibly significantly. I'm concerned that there is the presumption that there is no expiration for Acknowledgements. Does this mean that a PS must maintain these records for years if the App Server never reconnects? I would prefer a PS specified ACK timeout. 

Since our system doesn't have the concept of "half delivered" (an attempt was made to send the notification to the client, but no ACK/NAK was received), there's no difference between a User Agent never connecting nor returning a response regarding a notification delivery attempt, correct? I would prefer that no user connection information "leaks" back to the AS via the PS.

**Comment by brianraymor** [comment]
@jrconlin wrote _I'm concerned that there is the presumption that there is no expiration for Acknowledgements._ 

An acknowledgement expires when its related message TTL expires. This was discussed at [IETF93](https://www.ietf.org/proceedings/93/minutes/minutes-93-webpush):

_\- There was a general consensus to support “Full Reliability” whereby push and acknowledgement messages are both stored and retried until TTL expires._ 
_\- Whether TTL be same for both acknowledgment and push message need to be debated._

and separate TTL(s) was closed after IETF94 - See #40

**Comment by jrconlin** [comment]
@brianraymor Thanks, I was concerned because I did not know the outcome of #40, and only knew the discussion being held here. 

@idelpivnitskiy I would consider a TTL=0 message to be something of immediate value to the recipient (e.g. "Your toast is on fire" or "There's a parking spot available outside your building"). As such, they're effectively disposable, and the lack of an immediate ACK would infer a NAK. 

To be honest, the most reliable form of ACK/NAK would be the App and App Server. Currently the App Server sends the message through the Push Service, which hands to the User Agent, which hands to the Service Worker, which then hands to the App. That's a fair number of moving parts and hand offs where things might go awry. If a system wanted true reliability, it would have it's App signal back to the App Server when it positively acquired the message, or the App Server would note the lapse of the TTL without such acknowledgement as a NAK. The push service can only be as reliable as Murphy will allow.

**Comment by idelpivnitskiy** [comment]
> Since our system doesn't have the concept of "half delivered" (an attempt was made to send the notification to the client, but no ACK/NAK was received), there's no difference between a User Agent never connecting nor returning a response regarding a notification delivery attempt, correct? I would prefer that no user connection information "leaks" back to the AS via the PS.

@jrconlin I opened parallel thread to discuss this question: #110

**Comment by idelpivnitskiy** [comment]
@jrconlin Thanks for the explanation and example. Agree that my proposal will increase complexity of PS and it's requirements for the memory. And as there is no mandatory requirement that push messages with TTL=0 have to be deleted immediately we may leave it as is. If someone want to implement it, he may do this.
