### ISSUE TITLE
Prefer: wait=0 for Receiving Push Message Receipts

### ISSUE THREAD

**Issue by idelpivnitskiy** [webpush-wg/webpush-protocol#113]
Looks like the logic and [reliability level](https://www.ietf.org/proceedings/93/slides/slides-93-webpush-1.pdf) is the same for Receiving Push Message Receipts (6.3) and Receiving Push Messages for a Subscription (6). Will not be a problem to add useful feature for the AS too.

**Comment by martinthomson** [comment]
I'm not sure what your issue is here.  Would you mind restating it?

**Comment by brianraymor** [comment]
Symmetry? My interpretation is that this is a suggestion to add a **Prefer: wait=0** option to the Receiving Push Message Receipts section to allow application servers to have the same option for receiving receipts as user agents have for receiving messages. Something like:

_A application server can also request the contents of the receipt subscription resource immediately by including a Prefer header field [RFC7240] with a "wait" preference set to "0".  In response to this request, the push service MUST generate a server push for all receipts that have not yet been delivered._

**Comment by idelpivnitskiy** [comment]
@brianraymor Thank you! That's exactly what I mean.

Info about possible 204 (No Content) response also should be included:

> A 204 (No Content) status code with no associated server pushes indicates that no new receipts are presently available.

I can send a PR for this.

**Comment by brianraymor** [comment]
@idelpivnitskiy - a PR is not necessary. Since we're in **WGLC** and this has not been requested during the lifetime of the protocol design, it would be good for you to explore if there is strong implementer interest in the change on the mailing list. 

The Prefer: wait=0 makes sense for user agents on mobile devices with limited battery life. Although the proposal is symmetrical, it might be less useful or necessary for the application server. I don't have a strong opinion.
