### ISSUE TITLE
Acknowledgment reliability

### ISSUE THREAD

**Issue by martinthomson** [webpush-wg/webpush-protocol#18]

**Comment by brianraymor** [comment]
From my notes of the discussion on 4/7. The scenarios are:

**Application Server is unavailable**

This is the case where the PS receives an acknowledgement from the UA, but cannot push a receipt to the AS because the AS is temporarily unavailable and not listening.  Is a TTL for receipts required?

**Application Server receives but fails to fully process**

This is the case where the AS receives the receipt from the PS, but then crashes before it finishes processing (fails to save state). Are receipt acknowledgements required between the AS and PS - symmetrical to the UA and PS?

For both this issue and #17, @martinthomson suggests addressing at the application layer where the AS waits for the push TTL to expire and then re-sends important messages that require a receipt. The UA must then eliminate duplicates to avoid potentially annoying the user (if there is one).

**Comment by martinthomson** [comment]
Decision is to leave this open for now.  Will leave open with an note in the draft.

**Comment by DanDruta** [comment]
Application Server should be able to query the status of a request/confirmation, if it for some reason could not serve a result notification (e.g. its listener was down). But because failure to send a result notification is not always the AS’s fault, an optional / implementation-specific feature of a PS could be to retry the notification (subsequent questions e.g. retry limits/schedule are also implementation specific).

**Comment by ghost** [comment]
> Application Server should be able to query the status of a request/confirmation, if it for some reason could not serve a result notification (e.g. its listener was down).

My impression is that this works like the subscription endpoint. If the client sends an ack and the app server isn't listening for receipts, the push server will store and deliver the receipts the next time the app server reconnects.

App servers could also use `Prefer: wait=0` to request immediate delivery of stored acks.

Might be good to make this symmetry explicit in the spec, though.

**Edit**: Symmetry in the sense of storing acks and `Prefer`, but no corresponding ack from the app server (i.e., we don't want to "ack the acks"). Martin pointed out in IRC that making acks ephemeral simplifies a lot, though.

**Comment by martinthomson** [comment]
I've articulated the reasons that I disagree with this assessment in #17.  The actual value delivered is outweighed by the cost of providing the capability.

**Comment by martinthomson** [comment]
I think that we could support a HEAD/GET request for the message resource so that application servers can query the status of a message, primarily whether it has been delivered.

**Comment by brianraymor** [comment]
As [captured](https://www.ietf.org/proceedings/93/minutes/minutes-93-webpush) in the IETF 93 meeting minutes:

_There was a general consensus to support “Full Reliability” whereby push and acknowledgement messages are both stored and retried until TTL expires._

Push messages are stored and retried.
Acknowledgments are stored and retried.
At the TTL, the push service gives up.
