### ISSUE TITLE
Push-Receipt or link relation?

### ISSUE THREAD

**Issue by martinthomson** [webpush-wg/webpush-protocol#61]
Is there any value in using a link relation type for the receipt subscription rather than a new header field?  We already have to define the link relation type, so maybe it can save on a bit of protocol machinery.

**Comment by brianraymor** [comment]
While considering this, I noticed an editorial error in Section 10.2 where the link relation is referenced as urn:ietf:push:receipt**s** instead of urn:ietf:push:receipt which is used throughout the rest of the draft.

Using a link relation might be more consistent - not sure that it saves on _protocol machinery_?

Are you proposing to replace the Push-Receipt header with a new link relation - potentially there would be:
- push:receipts - to create new receipt subscriptions
- push:receipt - a specific receipt subscription

**Comment by martinthomson** [comment]
Yes, there are the same number of moving parts.  My mistake.

Just remembered the actual reason for opening the issue.  The HTTP working group often state that header fields need to have wide applicability for them to be defined, otherwise the data they carry is best carried in payload bodies.  The same restriction does not apply to link relations.
